import 'dart:io';

class Global {
  static File? pic;
  static String fName = '';
  static String bDate = '';
  static String phone = '';

  static List<Map<String, dynamic>> item = [
    {
      'name': 'Neckless',
      'image': 'assets/images/neck.jpg',
      'itemList': neckless,
    },
    {
      'name': 'Braclate',
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.10_PM-removebg-preview.png',
      'itemList': braclate,
    },
    {
      'name': 'Earring',
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.09_AM__4_-removebg-preview.png',
      'itemList': earring,
    },
    {
      'name': 'Ring',
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.36_PM__2_-removebg-preview.png',
      'itemList': ring,
    },
    {
      'name': 'Heels',
      'image': 'assets/images/heels2.jpg',
      'itemList': heels,
    },
    {
      'name': 'Flat',
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.42_PM-removebg-preview.png',
      'itemList': flat,
    },
    {
      'name': 'Shoose',
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.23_PM__1_-removebg-preview.png',
      'itemList': shoose,
    },
    {
      'name': 'Purse',
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.54_PM__3_-removebg-preview.png',
      'itemList': purse,
    },
    {
      'name': 'Bengals',
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.47_PM__1_-removebg-preview.png',
      'itemList': bengals,
    },
    {
      'name': 'Mat Lipstick',
      'image': 'assets/images/lipstik10.jpg',
      'itemList': lipstikM,
    },
    {
      'name': 'Liquid Lipstick',
      'image': 'assets/images/lilick10.jpg',
      'itemList': lipsticL,
    },
    {
      'name': 'Watch',
      'image': 'assets/images/watch.jpg',
      'itemList': watch,
    },
    {
      'name': 'Anklet',
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM__7_-removebg-preview.png',
      'itemList': anklet,
    },
    {
      'name': 'Hairpin',
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.44.34_AM__1_-removebg-preview.png',
      'itemList': hairpin,
    },
    {
      'name': 'Perfume',
      'image': 'assets/images/p.jpg',
      'itemList': perfume,
    },
  ];
  static List<Map<dynamic, dynamic>> neckless = [
    {
      'name': 'neckless',
      'image': 'assets/images/neck1.jpg',
      'price': 450,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/neck2.jpg',
      'price': 300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/neck3.jpg',
      'price': 350,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/necck4.jpg',
      'price': 650,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/neck5.jpg',
      'price': 500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/neck6.jpg',
      'price': 300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/neck7.jpg',
      'price': 400,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/neck8.jpg',
      'price': 580,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/neck9.jpg',
      'price': 500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/neck10.jpg',
      'price': 610,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/neckk11-removebg-preview.png',
      'price': 800,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'neckless',
      'image': 'assets/images/neck.jpg',
      'price': 250,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> braclate = [
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.10_PM__3_-removebg-preview.png',
      'price': 2100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.10_PM__6_-removebg-preview.png',
      'price': 1500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.11_PM__1_-removebg-preview.png',
      'price': 1100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.10_PM__2_-removebg-preview.png',
      'price': 1560,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.10_PM__1_-removebg-preview.png',
      'price': 2500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.10_PM__5_-removebg-preview.png',
      'price': 1540,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.10_PM__4_-removebg-preview.png',
      'price': 1800,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.11_PM-removebg-preview.png',
      'price': 450,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.10_PM-removebg-preview.png',
      'price': 2580,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.11_PM__2_-removebg-preview.png',
      'price': 650,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.11_PM__4_-removebg-preview.png',
      'price': 550,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.11.11_PM__4_-removebg-preview.png',
      'price': 460,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'braclate',
    }
  ];
  static List<Map<dynamic, dynamic>> earring = [
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.09_AM__8_-removebg-preview.png',
      'price': 550,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.27_AM-removebg-preview.png',
      'price': 350,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.10_AM-removebg-preview.png',
      'price': 280,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.27_AM__1_-removebg-preview.png',
      'price': 490,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.09_AM__7_-removebg-preview.png',
      'price': 420,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.09_AM__6_-removebg-preview.png',
      'price': 560,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.09_AM__5_-removebg-preview.png',
      'price': 650,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.09_AM__4_-removebg-preview.png',
      'price': 890,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.09_AM__3_-removebg-preview.png',
      'price': 880,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.09_AM__2_-removebg-preview.png',
      'price': 200,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.09_AM__1_-removebg-preview.png',
      'price': 250,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.28.09_AM-removebg-preview.png',
      'price': 990,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'earring',
    }
  ];
  static List<Map<dynamic, dynamic>> ring = [
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.49_PM__1_-removebg-preview.png',
      'price': 290,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'ring',
      'remove': false,
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.49_PM-removebg-preview.png',
      'price': 225,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.37_PM-removebg-preview.png',
      'price': 300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.36_PM__8_-removebg-preview.png',
      'price': 150,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.36_PM__7_-removebg-preview.png',
      'price': 350,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.36_PM__6_-removebg-preview.png',
      'price': 500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.36_PM__5_-removebg-preview.png',
      'price': 490,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.36_PM__4_-removebg-preview.png',
      'price': 330,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.36_PM__3_-removebg-preview.png',
      'price': 550,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.36_PM__2_-removebg-preview.png',
      'price': 450,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.36_PM__1_-removebg-preview.png',
      'price': 600,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-13_at_1.21.36_PM-removebg-preview.png',
      'price': 770,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'ring',
    },
  ];
  static List<Map<dynamic, dynamic>> heels = [
    {
      'image': 'assets/images/heeels6.jpg',
      'price': 780,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'heels',
    },
    {
      'image': 'assets/images/heels1.jpg',
      'price': 910,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'heels',
    },
    {
      'image': 'assets/images/heels2.jpg',
      'price': 1300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'heels',
    },
    {
      'image': 'assets/images/heels3.jpg',
      'price': 1200,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'heels',
    },
    {
      'image': 'assets/images/heels4.jpg',
      'price': 2000,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'heels',
    },
    {
      'image': 'assets/images/heels5.jpg',
      'price': 3000,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'heels',
    },
    {
      'image': 'assets/images/heels7.jpg',
      'price': 2300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'heels',
    },
    {
      'image': 'assets/images/heels.jpg',
      'price': 1800,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'heels',
      'remove': false,
    },
    {
      'image': 'assets/images/heels9.jpg',
      'price': 850,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'heels',
      'remove': false,
    },
    {
      'image': 'assets/images/heels10.jpg',
      'price': 980,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'heels',
      'remove': false,
    },
    {
      'image': 'assets/images/heels11.jpg',
      'price': 1500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'heels',
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> flat = [
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.42_PM__2_-removebg-preview.png',
      'price': 1100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'flat',
      'remove': false,
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.42_PM__1_-removebg-preview.png',
      'price': 1500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'flat',
      'remove': false,
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.42_PM-removebg-preview.png',
      'price': 2600,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'flat',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.41_PM__3_-removebg-preview.png',
      'price': 2000,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'flat',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.41_PM__2_-removebg-preview.png',
      'price': 1555,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'flat',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.41_PM__1_-removebg-preview.png',
      'price': 2100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'flat',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.41_PM-removebg-preview.png',
      'price': 2210,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'flat',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.20_PM__2_-removebg-preview.png',
      'price': 3280,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'flat',
      'remove': false,
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.20_PM__1_-removebg-preview.png',
      'price': 950,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'flat',
      'remove': false,
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.20_PM-removebg-preview.png',
      'price': 1650,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'flat',
      'remove': false,
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.14.19_PM__1_-removebg-preview.png',
      'price': 3560,
      'cart': false,
      'name': 'flat',
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> shoose = [
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.07.46_PM-removebg-preview.png',
      'price': 1600,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.47_PM__1_-removebg-preview.png',
      'price': 1800,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.47_PM-removebg-preview.png',
      'price': 2700,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.46_PM-removebg-preview.png',
      'price': 2190,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.24_PM__2_-removebg-preview.png',
      'price': 2000,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.24_PM__1_-removebg-preview.png',
      'price': 2600,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.24_PM-removebg-preview.png',
      'price': 2300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.23_PM__3_-removebg-preview.png',
      'price': 3000,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.23_PM__2_-removebg-preview.png',
      'price': 1800,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.23_PM__1_-removebg-preview.png',
      'price': 4500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.23_PM-removebg-preview.png',
      'price': 1750,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'shoose',
    },
  ];
  static List<Map<dynamic, dynamic>> purse = [
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.54_PM__2_-removebg-preview.png',
      'price': 1900,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'purse',
      'remove': false,
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.54_PM__1_-removebg-preview.png',
      'price': 3600,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'purse',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.54_PM-removebg-preview.png',
      'price': 1700,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'purse',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.40_PM__1_-removebg-preview.png',
      'price': 2300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'purse',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.40_PM-removebg-preview.png',
      'price': 4600,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'purse',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.39_PM__3_-removebg-preview.png',
      'price': 3400,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'purse',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.39_PM__2_-removebg-preview.png',
      'price': 2100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'purse',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.39_PM__1_-removebg-preview.png',
      'price': 1500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'purse',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.39_PM-removebg-preview.png',
      'price': 1300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'purse',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_12.01.54_PM__3_-removebg-preview.png',
      'price': 4000,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'purse',
    },
  ];
  static List<Map<dynamic, dynamic>> bengals = [
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.05.22_PM__1_-removebg-preview.png',
      'price': 450,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'bengals',
      'remove': false,
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.05.22_PM-removebg-preview.png',
      'price': 550,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'bengals',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.48_PM__1_-removebg-preview.png',
      'price': 440,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'bengals',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.48_PM-removebg-preview.png',
      'price': 300,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'bengals',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.47_PM__7_-removebg-preview.png',
      'price': 380,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'bengals',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.47_PM__6_-removebg-preview.png',
      'price': 290,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'bengals',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.47_PM__5_-removebg-preview.png',
      'price': 400,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'bengals',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.47_PM__4_-removebg-preview.png',
      'price': 460,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'bengals',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.47_PM__3_-removebg-preview.png',
      'price': 660,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'bengals',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.47_PM__2_-removebg-preview.png',
      'price': 550,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'bengals',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.47_PM__1_-removebg-preview.png',
      'price': 880,
      'cart ': false,
      'i': 0,
      'total': 0,
      'name': 'bengals',
      'add': false,
      'remove': false,
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.04.47_PM-removebg-preview.png',
      'price': 690,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'bengals',
    },
  ];
  static List<Map<dynamic, dynamic>> lipstikM = [
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.25.42_PM-removebg-preview.png',
      'price': 1800,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Mat Lipstick',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.19.52_PM-removebg-preview.png',
      'price': 2800,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Mat Lipstick',
    },
    {
      'image': 'assets/images/mat2.jpg',
      'price': 560,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Mat Lipstick',
    },
    {
      'image': 'assets/images/mit1.jpg',
      'price': 950,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Mat Lipstick',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.25.56_PM-removebg-preview.png',
      'price': 650,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Mat Lipstick',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.25.43_PM__3_-removebg-preview.png',
      'price': 880,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Mat Lipstick',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.25.43_PM__1_-removebg-preview.png',
      'price': 2100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Mat Lipstick',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.25.43_PM-removebg-preview.png',
      'price': 1800,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Mat Lipstick',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.25.42_PM__4_-removebg-preview.png',
      'price': 1600,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Mat Lipstick',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.25.42_PM__3_-removebg-preview.png',
      'price': 990,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'Mat Lipstick',
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> lipsticL = [
    {
      'image': 'assets/images/lillick7.jpg',
      'price': 850,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Liquid Lipstick',
    },
    {
      'image': 'assets/images/lillick9.jpg',
      'price': 1500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Liquid Lipstick',
    },
    {
      'image': 'assets/images/lli2.jpg',
      'price': 990,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Liquid Lipstick',
    },
    {
      'image': 'assets/images/lilpllicck8.jpg',
      'price': 910,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Liquid Lipstick',
    },
    {
      'image': 'assets/images/liplick4.jpg',
      'price': 2300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Liquid Lipstick',
    },
    {
      'image': 'assets/images/liplick5.jpg',
      'price': 1150,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Liquid Lipstick',
    },
    {
      'image': 'assets/images/liplick6.jpg',
      'price': 2105,
      'name': 'Liquid Lipstick',
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'image': 'assets/images/liplick11.jpg',
      'price': 1520,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Liquid Lipstick',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.25.43_PM__2_-removebg-preview.png',
      'price': 1670,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'Liquid Lipstick',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.25.42_PM__2_-removebg-preview.png',
      'price': 1500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'name': 'Liquid Lipstick',
      'remove': false,
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.25.42_PM__1_-removebg-preview.png',
      'price': 1600,
      'cart': false,
      'i': 0,
      'name': 'Liquid Lipstick',
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> watch = [
    {
      'image': 'assets/images/watch1.jpg',
      'price': 1500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
    {
      'image': 'assets/images/watch2.jpg',
      'price': 1280,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
    {
      'image': 'assets/images/watch3.jpg',
      'price': 2800,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
    {
      'image': 'assets/images/watch4.jpg',
      'price': 3900,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
    {
      'image': 'assets/images/watch5.jpg',
      'price': 1590,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
    {
      'image': 'assets/images/watch6.jpg',
      'price': 4000,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
    {
      'image': 'assets/images/watch7.jpg',
      'price': 3700,
      'cart': false,
      'name': 'watch',
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'image': 'assets/images/watch8.jpg',
      'price': 1800,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
    {
      'image': 'assets/images/watch9.jpg',
      'price': 2900,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
    {
      'image': 'assets/images/watch10.jpg',
      'price': 2400,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
    {
      'image': 'assets/images/watch11.jpg',
      'price': 1300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
    {
      'image': 'assets/images/watch.jpg',
      'price': 3500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'watch',
    },
  ];
  static List<Map<dynamic, dynamic>> anklet = [
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM__8_-removebg-preview.png',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM__7_-removebg-preview.png',
      'price': 120,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM__6_-removebg-preview.png',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM__9_-removebg-preview.png',
      'price': 50,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM__5_-removebg-preview.png',
      'price': 90,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM__4_-removebg-preview.png',
      'price': 60,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM__3_-removebg-preview.png',
      'price': 75,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM__2_-removebg-preview.png',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM__1_-removebg-preview.png',
      'price': 130,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.03_PM-removebg-preview.png',
      'price': 145,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.02_PM__1_-removebg-preview.png',
      'price': 110,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_1.06.02_PM-removebg-preview.png',
      'price': 135,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'anklet',
    },
  ];
  static List<Map<dynamic, dynamic>> hairpin = [
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.44.34_AM-removebg-preview.png',
      'price': 530,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.44.33_AM__1_-removebg-preview.png',
      'price': 450,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.44.33_AM-removebg-preview.png',
      'price': 150,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.43.24_AM__3_-removebg-preview.png',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.43.24_AM__2_-removebg-preview.png',
      'price': 220,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.43.24_AM__1_-removebg-preview.png',
      'price': 360,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.43.24_AM-removebg-preview.png',
      'price': 490,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.43.23_AM__3_-removebg-preview.png',
      'price': 300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.43.23_AM__2_-removebg-preview.png',
      'price': 120,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.44.34_AM__1_-removebg-preview.png',
      'price': 200,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.43.23_AM__1_-removebg-preview.png',
      'price': 450,
      'cart ': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
    {
      'image':
          'assets/images/WhatsApp_Image_2022-12-14_at_11.43.23_AM-removebg-preview.png',
      'price': 320,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'hairpin',
    },
  ];
  static List<Map<dynamic, dynamic>> perfume = [
    {
      'image': 'assets/images/p1.jpg',
      'price': 1100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p2.jpg',
      'price': 1700,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p3.jpg',
      'price': 1900,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p4.jpg',
      'price': 2300,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p5.jpg',
      'price': 1600,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p6.jpg',
      'price': 1200,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p7.jpg',
      'price': 2100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p8.jpg',
      'price': 3000,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p9.jpg',
      'price': 2500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p10.jpg',
      'price': 2000,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p11.jpg',
      'price': 1500,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
      'name': 'perfume',
    },
    {
      'image': 'assets/images/p.jpg',
      'price': 1300,
      'cart': false,
      'name': 'perfume',
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    }
  ];

  static Set<Map<dynamic, dynamic>> cart = {};
  static List<Map<dynamic, dynamic>> finalCart = [];

  static num totalBill = 0;
}
